In [ ]:
import numpy as np
a = np.arange(1,21)
print(a)
b = a.reshape(4, 5)
print(b)
#c = b.replace(max(axis=1), 0)

c = b.max(axis=1)

#row_maxes = c.max(axis=1).reshape(-1, 1)
#c[:] = np.where(c == row_maxes, 0, 1)

print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 5 10 15 20]


In [5]:
class Employee:
    """
    Generic Employee class with name, family, salary and department
    """

    # data member to count the number of Employees
    no_of_employees = 0

    def __init__(self, name, family_name, salary, department):
        self.__name = name
        self.__family_name = family_name
        self.salary = salary
        self.__department = department
        Employee.no_of_employees += 1

    @staticmethod
    def average_salary(employees):
        """
        function to average salary
        """
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.no_of_employees


class FulltimeEmployee(Employee):
    """
    Full Time Employee is a sub class of Employee
    """

    def __init__(self, name, family_name, salary, department):
        super().__init__(name, family_name, salary, department)

    def full_time_benefits(self):
        print("Few benefits as full time employee.")


def main():
    employees = []
    fte1 = FulltimeEmployee("Employee1", "FamilyName1", 120000, "Management")
    fte1.full_time_benefits()
    employees.append(fte1)
    fte2 = FulltimeEmployee("Employee2", "FamilyName2", 180000, "RnD")
    employees.append(fte2)
    emp1 = Employee("Employee3", "FamilyName3", 160000, "Marketing")
    employees.append(emp1)
    emp2 = Employee("Employee4", "FamilyName4", 135000, "HR")
    employees.append(emp2)
    print("Average salary:", FulltimeEmployee.average_salary(employees))


if __name__ == "__main__":
    main()


Few benefits as full time employee.
Average salary: 148750.0
